name: Style Dictionary Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Style Dictionary
        run: npm install style-dictionary@latest

      - name: Build Style Dictionary
        run: npx style-dictionary build

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          git add .
          git commit -m "Updated style dictionary"
          git push